spring:
  datasource:
    url: ...
    username: ...
    password: ...
    driver-class-name: ...
  hikari:
    connection-test-query: ...
    minimum-idle: ...
    maximum-pool-size: ...
    pool-name: ...
  jpa:
    hibernate:
      ddl-auto: ...
    show-sql: ...
    properties:
      hibernate:
        dialect: ...
  application:
    name: ...
jwt:
  secretAccess: ...
  secretRefresh: ...
  lifetime: ...
  lifetimeRefresh: ...
server:
  port: ...
  ssl:
    key-store: ...
    key-store-password: ...
    key-store-type: ...
    key-alias: ...
vk:
  client: ...
  secret: ...
  authorization-grant-type: ...
  scope: ...
  response-type: ...
  version: ...
  redirect-uri: ...
  token: https://oauth.vk.com/access_token
  auth-url: https://oauth.vk.com/authorize
  main-front-page: ...
  error-page: ...