server:
  port: ...
spring:
  datasource:
    url: ...
    username: ...
    password: ...
    driver-class-name: ...
  hikari:
    connection-test-query: ...
    minimum-idle: ...
    maximum-pool-size: ...
    pool-name: ...
  jpa:
    hibernate:
      ddl-auto: ...
    show-sql: ...
    properties:
      hibernate:
        dialect: ...
  application:
    name: ...
jwt:
  secretAccess: ...
  secretRefresh: ...
  lifetime: ...
  lifetimeRefresh: ...
urls:
  searcher:
    domain: ...
    add-path: ...
    provide-path: ...
    search-path:
      solution: ...
      project: ...
      document: ...